In [5]:
import pandas as pd
df_corporate= pd.read_excel("corporate.xlsx")
df_corporate = df_corporate.drop(['_airbyte_ab_id', '_airbyte_emitted_at','_airbyte_additional_properties','source_file_path'], axis=1)

df_corporate.head()

,zip,city,int1,int2,int3,int4,int5,int6,int7,str1,...,nextforeigntaxreviewdate,principle_placeoperation,risk_profile_expiry_date,foreignacctaxreportingreq,foreigntaxreportingstatus,foreigntaxreportingcountry,keycontact_personname_alt1,countryofprincipaloperation,customer_level_provisioning,updated_at
0,0,KATHM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,...,NaN,NP,NaN,NaN,NaN,NaN,NaN,NP,NaN,2024-08-07 06:36:05.388
1,.,SUNSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-07 06:36:05.388
2,0,BHAKT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NP,NaN,NaN,NaN,NaN,NaN,NP,NaN,2024-08-07 06:36:05.388
3,.,TANAH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-07 06:36:05.388
4,.,SUNSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-07 06:36:05.388

In [6]:
df_corporate.to_csv('corporate_masked.csv', index=False)