In [230]:
import pandas as pd
import random
from faker import Faker
import psycopg2

In [231]:

conn = psycopg2.connect(
    dbname="original",
    user="postgres",
    password="prashanta",
    host="localhost",
    port="5432"
)
# SQL query to fetch data
query = "SELECT * FROM accounts;"

# Load data into a pandas DataFrame
df = pd.read_sql_query(query, conn)


# Close the connection
conn.close()

# Display the DataFrame
df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\100642893.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,_airbyte_ab_id,_airbyte_emitted_at,cin,fax,pan,ssn,url,zip,city,flg1,...,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,_airbyte_additional_properties,source_file_path,updated_at
0,273b5728-535b-4106-8c31-ce5e48eee381,2024-08-05 07:02:37.777,None,None,NaN,None,None,977000,None,None,...,None,None,None,None,None,None,None,None,s3a://ai360nica/data/bronze/oracle/cbs/CRMUSER...,2024-08-07 06:29:18.596
1,70ced3d3-ad57-4433-a382-6ecbcc42fd90,2024-08-05 07:02:37.777,None,None,NaN,None,None,0,KATHM,None,...,None,None,None,None,None,None,None,None,s3a://ai360nica/data/bronze/oracle/cbs/CRMUSER...,2024-08-07 06:29:18.596
2,15e20dca-a337-44b5-b202-b299895336df,2024-08-05 07:02:37.777,None,None,NaN,None,None,977000,BUDAN,None,...,None,None,None,None,None,None,None,None,s3a://ai360nica/data/bronze/oracle/cbs/CRMUSER...,2024-08-07 06:29:18.596
3,5cf04c55-8085-4e86-ab6f-88904ceb2c6e,2024-08-05 07:02:37.777,None,None,NaN,None,None,977000,RAMNA,None,...,None,None,None,None,None,None,None,None,s3a://ai360nica/data/bronze/oracle/cbs/CRMUSER...,2024-08-07 06:29:18.596
4,8fb8b8e6-aa95-4344-bdbe-a49935add064,2024-08-05 07:02:37.777,None,None,104894561.0,None,None,12,BIRAT,None,...,None,None,None,None,None,None,None,None,s3a://ai360nica/data/bronze/oracle/cbs/CRMUSER...,2024-08-07 06:29:18.596

In [232]:
df = df.drop(['_airbyte_ab_id', '_airbyte_emitted_at',"source_file_path","_airbyte_additional_properties"], axis=1)
df.head()

,cin,fax,pan,ssn,url,zip,city,flg1,flg2,flg3,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
0,None,None,NaN,None,None,977000,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
1,None,None,NaN,None,None,0,KATHM,None,None,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
2,None,None,NaN,None,None,977000,BUDAN,None,None,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
3,None,None,NaN,None,None,977000,RAMNA,None,None,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
4,None,None,104894561.0,None,None,12,BIRAT,None,None,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [233]:
#cust_type generation
import numpy as np
def get_cust_type(df):
    df= df.copy()
    condition =  (df["constitution_code"] == "INDIJ") | (df["constitution_code"] == "INDIV")
    df['cust_type'] = np.where(condition,"INDIVIDUAL","LEGAL")
    return df



df = get_cust_type(df)
df[["cust_type","constitution_code"]].head(7)

    cust_type constitution_code
0  INDIVIDUAL             INDIV
1       LEGAL             OTHER
2  INDIVIDUAL             INDIV
3  INDIVIDUAL             INDIJ
4  INDIVIDUAL             INDIV
5  INDIVIDUAL             INDIV
6       LEGAL              USTS

In [234]:
# CIF_ID Generation
import pandas as pd
import numpy as np

def generate_cif_id(code):
    if code == "INDIVIDUAL":
        prefix = "DLNIND"
    elif code == "LEGAL":
        prefix = "DLNLEG"
    else:
        return ""  
    
    random_digits = str(np.random.randint(1000000, 9999999))
    return prefix + random_digits


df["cif_id"] = df["cust_type"].apply(generate_cif_id)
df.head()

,cin,fax,pan,ssn,url,zip,city,flg1,flg2,flg3,...,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at,cif_id
0,None,None,NaN,None,None,977000,None,None,None,None,...,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596,DLNIND6192752
1,None,None,NaN,None,None,0,KATHM,None,None,None,...,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596,DLNLEG8986190
2,None,None,NaN,None,None,977000,BUDAN,None,None,None,...,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596,DLNIND5673051
3,None,None,NaN,None,None,977000,RAMNA,None,None,None,...,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596,DLNIND9675443
4,None,None,104894561.0,None,None,12,BIRAT,None,None,None,...,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596,DLNIND4038457

In [235]:
df["cif_id"].nunique()

125

In [236]:
import numpy as np
import random


df["marital_status"] = np.where(
    df["cust_type"] == "INDIVIDUAL",
    np.random.choice([True, False],size=len(df), p=[0.62, 0.38]),
    ""
)
df[["cust_type","marital_status"]].head(5)

    cust_type marital_status
0  INDIVIDUAL           True
1       LEGAL
2  INDIVIDUAL           True
3  INDIVIDUAL          False
4  INDIVIDUAL           True

In [237]:
selected_columns = [
    "cif_id",
    "orgkey",
    "cust_first_name",
    "cust_middle_name",
    "cust_last_name",
    "cust_dob",
    "cust_type",
    "gender",
    "marital_status",
    "education",
    "pan",
    "email",
    "preferredphone"
]
remaining_columns = [col for col in df.columns if col not in selected_columns]

In [238]:
new_df = df[selected_columns + remaining_columns]
new_df.head()

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
0,DLNIND6192752,319749297,SHYAM,None,CHAUDHARY,1988-02-17T00:00:00.000000,INDIVIDUAL,F,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
1,DLNLEG8986190,R24249553,None,None,NIC BANK-LOAN PROCESSING FEE,1900-01-01T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
2,DLNIND5673051,R28893337,PRADYUMNA,LAL,RAJBAMSHI,1961-12-06T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
3,DLNIND9675443,R66368828,CHANDESHWAR,SAHUTELI/SHAMBHUKUMAR,SAH,1965-07-16T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
4,DLNIND4038457,R02063811,JAGADISH,PRASAD,AGRAWAL,1943-04-05T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [239]:
cust_Ind = new_df[new_df["cust_type"]=="INDIVIDUAL"]
cust_Ind.head(80)

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
0,DLNIND6192752,319749297,SHYAM,None,CHAUDHARY,1988-02-17T00:00:00.000000,INDIVIDUAL,F,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
2,DLNIND5673051,R28893337,PRADYUMNA,LAL,RAJBAMSHI,1961-12-06T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
3,DLNIND9675443,R66368828,CHANDESHWAR,SAHUTELI/SHAMBHUKUMAR,SAH,1965-07-16T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
4,DLNIND4038457,R02063811,JAGADISH,PRASAD,AGRAWAL,1943-04-05T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
5,DLNIND6111614,R00061514,BIRENDRA BAHADUR,None,NEUPANE,1978-06-13T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,DLNIND3809257,R01911511,TIKA,None,KUMARI PADHYA,1959-01-27T00:00:00.000000,INDIVIDUAL,F,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
121,DLNIND1694858,R01911516,BHARATI,None,KUMARI KHATRI,1997-09-15T00:00:00.000000,INDIVIDUAL,F,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
122,DLNIND8408194,R01911519,BASANTI,None,DAMAI,1968-04-22T00:00:00.000000,INDIVIDUAL,F,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
123,DLNIND6126826,R01911512,BUDAI,None,SAH,1971-05-05T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
124,DLNIND6282618,R01901407,SAGAR,None,NEUPANE,1999-08-28T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [240]:
print(len(cust_Ind))

71

In [241]:
df = pd.read_csv("shuffled_data.csv")
df = df.iloc[0:71]

In [242]:
print(len(df))

71

In [243]:
cust_Ind["cust_first_name"] = df["cust_first_name"].values
cust_Ind["name"] = df["cust_first_name"].values+" " +df["cust_middle_name"].values+ " " + df["cust_last_name"].values
cust_Ind["cust_middle_name"] = df["cust_middle_name"].values
cust_Ind["cust_last_name"] = df["cust_last_name"].values
cust_Ind["gender"] = df["gender"].values
cust_Ind.head(80)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\822451688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_Ind["cust_first_name"] = df["cust_first_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\822451688.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_Ind["name"] = df["cust_first_name"].values+" " +df["cust_middle_name"].values+ " " + df["cust_last_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\822451688.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_Ind["cust_middle_name"] = df["cust_middle_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\822451688.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_Ind["cust_last_name"] = df["cust_last_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\822451688.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_Ind["gender"] = df["gender"].values

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
0,DLNIND6192752,319749297,Buddhiraj,Bishal,Sharma,1988-02-17T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
2,DLNIND5673051,R28893337,Pramil,Krishna,Neupane,1961-12-06T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
3,DLNIND9675443,R66368828,Shirish,Gopal,Thapa,1965-07-16T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
4,DLNIND4038457,R02063811,Hina,Devi,Bhattarai,1943-04-05T00:00:00.000000,INDIVIDUAL,F,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
5,DLNIND6111614,R00061514,Poshan,Bahadur,Thapa,1978-06-13T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,DLNIND3809257,R01911511,Heli,Saraswati,Timalsina,1959-01-27T00:00:00.000000,INDIVIDUAL,F,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
121,DLNIND1694858,R01911516,Pranij,Bibek,Shrestha,1997-09-15T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
122,DLNIND8408194,R01911519,Sanjita,Kumar,Pandey,1968-04-22T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
123,DLNIND6126826,R01911512,Prajina,Kumari,Pandey,1971-05-05T00:00:00.000000,INDIVIDUAL,F,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
124,DLNIND6282618,R01901407,Nirvan,Lal,Thakuri,1999-08-28T00:00:00.000000,INDIVIDUAL,M,False,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [244]:
df = pd.read_csv("company_name.csv")
df = df.iloc[0:54]
df.head(60)

                             cust_first_name cust_type
0                  TANAHUN DIGITAL PVT. LTD.     LEGAL
1                PYUTHAN LOGISTICS PVT. LTD.     LEGAL
2              PATHIVARA LOGISTICS PVT. LTD.     LEGAL
3                            DLYTICA ACADEMY     LEGAL
4                    PARSA TRADING PVT. LTD.     LEGAL
5               MANANG HOSPITALITY PVT. LTD.     LEGAL
6   RUPA SAVINGS AND CREDIT COOPERATIVE LTD.     LEGAL
7              SAGARMATHA CLOTHING PVT. LTD.     LEGAL
8                   SYANGJA REAL ESTATE LTD.     LEGAL
9           KANCHANJUNGA LOGISTICS PVT. LTD.     LEGAL
10          KAILASH PRINTING PRESS PVT. LTD.     LEGAL
11                     SUNSARI VENTURES LTD.     LEGAL
12              SAGARMATHA TRADERS PVT. LTD.     LEGAL
13            SINDHUPALCHOWK MEDIA PVT. LTD.     LEGAL
14                DLYTICA HOSPITAL PVT. LTD.     LEGAL
15                   SURKHET AGRO CO-OP LTD.     LEGAL
16            KAVREPALANCHOK MEDIA PVT. LTD.     LEGAL
17                    MANANG HYDROPOWER LTD.     LEGAL
18            NEPAL HERITAGE TOURS PVT. LTD.     LEGAL
19           PALPA PHARMACEUTICALS PVT. LTD.     LEGAL
20               TAMOR ELECTRONICS PVT. LTD.     LEGAL
21            HIMAL DAIRY PRODUCTS PVT. LTD.     LEGAL
22             SARLAHI ENGINEERING PVT. LTD.     LEGAL
23                BARDIYA SECURITY PVT. LTD.     LEGAL
24                 LUMBINI TRAVELS PVT. LTD.     LEGAL
25                   KHOTANG FOODS PVT. LTD.     LEGAL
26               BIRGUNJ CHEMICALS PVT. LTD.     LEGAL
27             ROLPA CONSTRUCTIONS PVT. LTD.     LEGAL
28           LUMBINI INTERNATIONAL PVT. LTD.     LEGAL
29                EVEREST FOOTWEAR PVT. LTD.     LEGAL
30       MAHENDRANAGAR CONSULTANCY PVT. LTD.     LEGAL
31               MUSTANG CARPENTRY PVT. LTD.     LEGAL
32                   MYAGDI ENTERPRISES LTD.     LEGAL
33                 SOLU HYDROPOWER PVT. LTD.     LEGAL
34                SYANGJA FOOTWEAR PVT. LTD.     LEGAL
35                  RUKUM CO-OP FINANCE LTD.     LEGAL
36                     ANNAPURNA HOTELS LTD.     LEGAL
37     BHIMSEN AGRICULTURAL COOPERATIVE LTD.     LEGAL
38        SARLAHI PLASTIC PRODUCTS PVT. LTD.     LEGAL
39                   SINDHULI AGRO PVT. LTD.     LEGAL
40                  NEPAL FINANCE GROUP LTD.     LEGAL
41                PALPA HEALTHCARE PVT. LTD.     LEGAL
42             MANASLU HOSPITALITY PVT. LTD.     LEGAL
43              SHREE KRISHNA FOUNDATION NGO     LEGAL
44           HIMALAYAN CONSULTANCY PVT. LTD.     LEGAL
45                 BARDIA BUILDERS PVT. LTD.     LEGAL
46                PHEWA AUTO PARTS PVT. LTD.     LEGAL
47          KALINCHOWK REAL ESTATE PVT. LTD.     LEGAL
48                 JAJARKOT DAIRY CO-OP LTD.     LEGAL
49          BIRATNAGAR AUTOMOBILES PVT. LTD.     LEGAL
50             JUMLA FOOD PRODUCTS PVT. LTD.     LEGAL
51                SUNSARI MANUFACTURING LTD.     LEGAL
52                       NEPAL AIRLINES LTD.     LEGAL
53                 SUNSARI DIGITAL PVT. LTD.     LEGAL

In [245]:
print(len(df))

54

In [246]:
cust_leg = new_df[new_df["cust_type"]=="LEGAL"]
cust_leg.head()

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
1,DLNLEG8986190,R24249553,None,None,NIC BANK-LOAN PROCESSING FEE,1900-01-01T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
6,DLNLEG4110702,C00004434,None,None,BARPIPAL TOLE BATO UPAVAOKTA SAMITI,2019-01-22T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
7,DLNLEG1904642,R08272460,None,None,CRYSTAL OFFSET PRESS,1900-01-01T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
8,DLNLEG3476293,C00004439,None,None,ARJUN SUNCHANDI UDHYOG,2015-09-15T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
9,DLNLEG9135432,C00004426,None,None,ROYAL FURNITURE UDYOG,2019-01-31T00:00:00.000000,LEGAL,None,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [247]:
print(len(cust_leg))

54

In [250]:
cust_leg["cust_first_name"] = df["cust_first_name"].values
cust_leg["name"] = df["cust_first_name"].values
cust_leg["cust_middle_name"] = ""
cust_leg["cust_last_name"] = ""
cust_leg["gender"] = ""
cust_leg["gender"]
cust_leg.head(80)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\1729481619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_leg["cust_first_name"] = df["cust_first_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\1729481619.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_leg["name"] = df["cust_first_name"].values
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\1729481619.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_leg["cust_middle_name"] = ""
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\1729481619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_leg["cust_last_name"] = ""
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26936\1729481619.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cust_leg["gender"] = ""

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
1,DLNLEG8986190,R24249553,TANAHUN DIGITAL PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
6,DLNLEG4110702,C00004434,PYUTHAN LOGISTICS PVT. LTD.,,,2019-01-22T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
7,DLNLEG1904642,R08272460,PATHIVARA LOGISTICS PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
8,DLNLEG3476293,C00004439,DLYTICA ACADEMY,,,2015-09-15T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
9,DLNLEG9135432,C00004426,PARSA TRADING PVT. LTD.,,,2019-01-31T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
10,DLNLEG2163717,R22132679,MANANG HOSPITALITY PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
11,DLNLEG3486725,C00004442,RUPA SAVINGS AND CREDIT COOPERATIVE LTD.,,,2017-02-07T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
12,DLNLEG8333147,R48318099,SAGARMATHA CLOTHING PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
13,DLNLEG6054997,C00004445,SYANGJA REAL ESTATE LTD.,,,2019-02-04T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
14,DLNLEG9881958,C00004446,KANCHANJUNGA LOGISTICS PVT. LTD.,,,2018-06-11T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
15,DLNLEG2907902,C00004448,KAILASH PRINTING PRESS PVT. LTD.,,,2009-10-22T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
16,DLNLEG9415109,C00004447,SUNSARI VENTURES LTD.,,,2019-01-29T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
17,DLNLEG9774895,800520371,SAGARMATHA TRADERS PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
18,DLNLEG5684893,800520784,SINDHUPALCHOWK MEDIA PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
19,DLNLEG5187203,C00004452,DLYTICA HOSPITAL PVT. LTD.,,,2018-05-17T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
20,DLNLEG6367945,C00004449,SURKHET AGRO CO-OP LTD.,,,2019-01-28T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
21,DLNLEG1786400,C00004454,KAVREPALANCHOK MEDIA PVT. LTD.,,,2017-08-20T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
22,DLNLEG4051774,C00004455,MANANG HYDROPOWER LTD.,,,2019-01-29T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
23,DLNLEG4389703,C00004456,NEPAL HERITAGE TOURS PVT. LTD.,,,2019-02-07T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
24,DLNLEG1812387,C00004453,PALPA PHARMACEUTICALS PVT. LTD.,,,2013-02-10T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
25,DLNLEG2107976,C00004457,TAMOR ELECTRONICS PVT. LTD.,,,2019-02-07T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
26,DLNLEG6959280,C00004458,HIMAL DAIRY PRODUCTS PVT. LTD.,,,2018-01-03T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
27,DLNLEG9056971,C00004460,SARLAHI ENGINEERING PVT. LTD.,,,2019-02-05T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
34,DLNLEG5632677,R52273477,BARDIYA SECURITY PVT. LTD.,,,1986-08-17T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
41,DLNLEG8137654,R32157797,LUMBINI TRAVELS PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
42,DLNLEG2976610,C00038863,KHOTANG FOODS PVT. LTD.,,,2012-11-12T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
44,DLNLEG7430034,C00036463,BIRGUNJ CHEMICALS PVT. LTD.,,,2019-04-15T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
45,DLNLEG2017695,C00058395,ROLPA CONSTRUCTIONS PVT. LTD.,,,2021-07-23T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
49,DLNLEG9465143,R22133142,LUMBINI INTERNATIONAL PVT. LTD.,,,2009-09-13T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
51,DLNLEG2266354,I40510833,EVEREST FOOTWEAR PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
52,DLNLEG1613802,R90504419,MAHENDRANAGAR CONSULTANCY PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
53,DLNLEG6544198,J00518347,MUSTANG CARPENTRY PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
56,DLNLEG2067019,R02103112,MYAGDI ENTERPRISES LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
58,DLNLEG4429567,R04006533,SOLU HYDROPOWER PVT. LTD.,,,2007-03-20T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
59,DLNLEG3889666,R30091981,SYANGJA FOOTWEAR PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
60,DLNLEG5995055,R30090144,RUKUM CO-OP FINANCE LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
63,DLNLEG9273995,R39227100,ANNAPURNA HOTELS LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
65,DLNLEG9427803,R23114400,BHIMSEN AGRICULTURAL COOPERATIVE LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
70,DLNLEG3149190,R09128392,SARLAHI PLASTIC PRODUCTS PVT. LTD.,,,1994-03-08T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
71,DLNLEG1943860,C00082152,SINDHULI AGRO PVT. LTD.,,,2018-03-14T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
73,DLNLEG1179478,C00086423,NEPAL FINANCE GROUP LTD.,,,2017-11-20T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
74,DLNLEG5389721,R09403211,PALPA HEALTHCARE PVT. LTD.,,,2015-09-06T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
75,DLNLEG2834849,C00033937,MANASLU HOSPITALITY PVT. LTD.,,,2008-11-05T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
76,DLNLEG3950191,R42240201,SHREE KRISHNA FOUNDATION NGO,,,1994-05-27T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
77,DLNLEG7836284,R57501498,HIMALAYAN CONSULTANCY PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
78,DLNLEG7702443,R19041342,BARDIA BUILDERS PVT. LTD.,,,2010-02-17T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
79,DLNLEG4368214,C00012403,PHEWA AUTO PARTS PVT. LTD.,,,2014-04-09T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
80,DLNLEG2775863,R68384006,KALINCHOWK REAL ESTATE PVT. LTD.,,,2003-06-16T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
81,DLNLEG3069511,C00000865,JAJARKOT DAIRY CO-OP LTD.,,,2011-02-07T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
88,DLNLEG4688102,R01001079,BIRATNAGAR AUTOMOBILES PVT. LTD.,,,2000-12-27T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
92,DLNLEG1205260,R22133473,JUMLA FOOD PRODUCTS PVT. LTD.,,,1972-07-18T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
94,DLNLEG1420388,R46253427,SUNSARI MANUFACTURING LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
95,DLNLEG9233517,R09092002,NEPAL AIRLINES LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
96,DLNLEG2350002,RB1499113,SUNSARI DIGITAL PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [252]:
result = pd.concat([cust_Ind,cust_leg])
shuffled = result.sample(frac=1, random_state=42).reset_index(drop=True)

shuffled.head()

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,cust_dob,cust_type,gender,marital_status,education,...,sencitizenconversionflag,creditbureauscorevalidity,foreignacctaxreportingreq,foreigntaxreportingstatus,preferred_mobile_alert_no,credithistoryrequestedflag,foreigntaxreportingcountry,customer_level_provisioning,preferred_mobile_alert_type,updated_at
0,DLNIND8613742,R01516157,Suprim,Shankar,Acharya,1966-05-06T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
1,DLNIND3162611,R01651971,Prithivi,Kumar,Yadav,1993-02-28T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
2,DLNIND1414575,R09396490,Nawraj,Hari,Regmi,2013-01-09T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
3,DLNLEG2163717,R22132679,MANANG HOSPITALITY PVT. LTD.,,,1900-01-01T00:00:00.000000,LEGAL,,,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596
4,DLNIND1962912,R00580783,Shrikumar,Kumar,Sharma,2000-01-01T00:00:00.000000,INDIVIDUAL,M,True,None,...,None,None,None,None,None,None,None,None,None,2024-08-07 06:29:18.596

In [256]:
import pandas as pd
import numpy as np

def generate_email(data):
    if isinstance(data["cust_first_name"], str) and "PVT. LTD." in data["cust_first_name"]:
        name = data["cust_first_name"].replace("PVT. LTD.", "").strip().lower().replace(" ", "")
        
    elif pd.isna(data["cust_first_name"]):
        name = "unknown"
    else:
        name = str(data["cust_first_name"]).lower().replace(" ", "")
    
    num = str(np.random.randint(100, 999))
    
    if data["cust_type"] == "INDIVIDUAL":
        email = name + num + "@gmail.com"
    else:
        email = name + num + "@outlook.com"
    
    return email

shuffled["email"] = shuffled[["cust_first_name", "cust_type"]].apply(generate_email, axis=1)
shuffled["email"].head(15)

0                   suprim901@gmail.com
1                 prithivi948@gmail.com
2                   nawraj247@gmail.com
3      mananghospitality506@outlook.com
4                shrikumar260@gmail.com
5       tamorelectronics622@outlook.com
6                   hansha956@gmail.com
7      nepalairlinesltd.892@outlook.com
8     sarlahiengineering990@outlook.com
9                   poshan835@gmail.com
10                  aavaas926@gmail.com
11        bardiabuilders465@outlook.com
12                  sakhil651@gmail.com
13          khotangfoods425@outlook.com
14               anushikha775@gmail.com
Name: email, dtype: object

In [258]:
def generate_phone_number(data):
   return  "+977-98"+str(np.random.randint(10000000,99999999))

shuffled["preferredphone"] = shuffled["preferredphone"].apply(generate_phone_number)
shuffled["preferredphone"].head(10)

0    +977-9844611914
1    +977-9874242488
2    +977-9813072615
3    +977-9897136232
4    +977-9861829804
5    +977-9879795026
6    +977-9858207430
7    +977-9820857060
8    +977-9894941670
9    +977-9892382607
Name: preferredphone, dtype: object

In [ ]:
shuffled.head(99)

In [262]:
shuffled.to_csv('account_masked.csv', index=False)