In [1]:
import pandas as pd
df_gem_schm_parm= pd.read_excel("gen_schm_parm_table.xlsx")
df_gem_schm_parm.head()

,SET_ID,TS_CNT,BANK_ID,DEL_FLG,EEFC_FLG,END_DATE,FCNR_FLG,LCHG_TIME,RCRE_TIME,RULE_CODE,...,ISO_USER_TOD_GRNT_EXCP_CODE,ISTISNA_WORK_PROGRESS_BACID,SCRIPT_VALUE_DATE_EXCP_CODE,RENT_RECOVERY_LOSSLINE_BACID,ACCT_LINKED_INVT_ID_EXCP_CODE,PARLL_ISTISNA_PRFT_ACCT_BACID,PARLL_IST_INVSTMNT_ACCT_BACID,PAST_DUE_PENAL_INT_COLL_BACID,OVERIDE_DEF_MIN_BAL_PARAM_EXCP,updated_at
0,ALL,494,1,N,N,2099-12-31T00:00:00.000000,N,2024-08-08T12:21:09,2014-06-05T14:12:00.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-29 04:59:46.921
1,ALL,7,1,N,N,2099-12-31T00:00:00.000000,N,2024-08-08T18:16:41,2014-01-22T12:38:52,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRTLPFCO,NaN,2024-08-29 04:59:46.921
2,ALL,11,1,N,N,2099-12-31T00:00:00.000000,N,2024-08-14T15:25:45,2016-10-04T12:40:29,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-29 04:59:46.921
3,ALL,8,1,N,N,2099-12-31T00:00:00.000000,N,2024-08-14T15:26:01,2021-03-26T15:36:51,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-29 04:59:46.921
4,ALL,2,1,N,N,2099-12-31T00:00:00.000000,N,2024-08-15T17:40:46,2024-08-13T14:30:39,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRRR001,NaN,2024-08-29 04:59:46.921

In [2]:
df_gem_schm_parm.to_csv("gen_schm_parm_table_masked.csv",index=False)