In [1]:
import pandas as pd
df_merchant_qr=pd.read_excel("merchant_details.xlsx")
df_merchant_qr.head()

,_id,name,doing_business_as,pan_number,mobile_number,email_id,account_number,account_name,user_name,status,...,created_approve_date,modified_date,approved_date,approved_by,modified_by,is_pan_registered,introduced_by,business_registration_no,source_file_path,updated_at
0,43968,SHREE TIKULIGADH MA VI,SHREE TIKULIGADH MA VI,912345704.0,9857015912,9857015912@nica.com,F141000445852402,SHREE TIKULIGADH MA VI,9857015912@nica.com,ACTIVE,...,2020-03-06T13:21:42,NaN,2020-03-06T13:21:42,NaN,NaN,NaN,KOTHIHAWA BRANCH,2457,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
1,8650,ARJUN SUNCHANDI UDHYOG,ARJUN SUNCHANDI UDHYOG,602205809.0,9856042369,sunitasunar352@gmail.com,E641000443952402,ARJUN SUNCHANDI UDHYOG,sunitasunar352@gmail.com,ACTIVE,...,2019-04-28T09:53:04,NaN,2019-04-28T09:53:04,NaN,NaN,NaN,NaN,4709/072/073,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
2,306428,PINKY KABADI PASAL,PINKY KABADI PASAL,301463056.0,9815993973,sekh@gmail.com,P541000445452402,PINKY KABADI PASAL,sekh@gmail.com,ACTIVE,...,2019-12-23T16:32:10,2020-04-22T17:03:58,2019-12-23T16:32:10,NaN,NaN,NaN,DAMAK CHOWK BRANCH,154/10016/5/4,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
3,32681,CRYSTAL OFFSET PRESS,CRYSTAL OFFSET PRESS,304298275.0,9843159014,crystal.press6@gmail.com,0841827246052401,CRYSTAL OFFSET PRESS,crystal.press6@gmail.com,ACTIVE,...,2020-02-24T18:02:53,NaN,2020-02-24T18:02:53,NaN,NaN,NaN,Bhaktapur,464/067/68,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
4,283430,MUNNI LAL MANGI LAL,MUNNI LAL MANGI LAL,301454342.0,9855022111,9855022111@gmail.com,2240133473524004,MUNNI LAL MANGI LAL,9855022111@gmail.com,ACTIVE,...,2019-12-06T14:29:45,NaN,2019-12-06T14:29:45,NaN,NaN,NaN,BIRGUNJ BRANCH,4330/029,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904

In [2]:
df_acid_for=pd.read_csv(r"..\..\tbaadm\general_acct_mast_table\acid_foracid_masked.csv")
df_acid_for

,acid,acid_t,cif_id,foracid,foracid_t,pan,acct_num,acct_name
0,Q39620558,AC10370877,DLNIND1406504,2635752944296001,FA9627239668220084,PAN668645879,272396682200,Humacanta Bipin Thapa
1,Y110180600,AC41672289,DLNIND4211643,3414659520992004,FA3302344775994664,PAN697945863,23447759946,Sriti Kumari Thapa
2,O93531058,AC73584145,DLNIND4211643,O987952099252401,FA5553585851915269,PAN697945863,535858519152,Sriti Kumari Thapa
3,32559774,AC12345718,DLNLEG9334212,3241157797524004,FA2582732553674743,PAN353089449,827325536747,PALPA HEALTHCARE PVT. LTD.
4,889280082,AC47235600,DLNLEG6576494,0884459092002067,FA7171012596574289,PAN813377590,710125965742,NaN
...,...,...,...,...,...,...,...,...
4082,019325160,AC67969280,DLNIND9286944,001TD59898447011,FA8894858102271145,PAN140168943,948581022711,Veshraj Mainali
4083,019349668,AC42214177,DLNIND9286944,001TD59898447012,FA2052321391947965,PAN140168943,523213919479,Veshraj Mainali
4084,015926375,AC78549197,DLNIND9286944,001TD59898447003,FA2391574283942563,PAN140168943,915742839425,Veshraj Mainali
4085,016314347,AC49882479,DLNIND9286944,001TD59898447004,FA6320628849891407,PAN140168943,206288498914,Veshraj Mainali
4086,016728759,AC62000071,DLNIND9286944,001HL59898447005,FA3011644390102776,PAN140168943,116443901027,Veshraj Mainali

In [3]:
df_cif_mask=pd.read_csv(r"..\..\crmuser\account\cif_masked.csv")
df_cif_mask

,cif_id,orgkey,cust_first_name,cust_middle_name,cust_last_name,preferredphone,preferredname,preferredemail,email,gender,name,pan
0,DLNIND4568821,R01562055,Duman,Narayan,Neupane,-9833329213,Duman Narayan Neupane,ARYALPRABAL@GMAIL.COM,duman492@gmail.com,M,Duman Narayan Neupane,PAN714271279
1,DLNIND7235296,R01911512,Prajina,Devi,Maharjan,-9892306612,Prajina Devi Maharjan,na@nicasiabank.com,prajina427@gmail.com,F,Prajina Devi Maharjan,PAN503838478
2,DLNIND1406504,R02944296,Humacanta,Bipin,Thapa,-9856817476,Humacanta Bipin Thapa,dipeshshah4000@gmail.com,humacanta862@gmail.com,M,Humacanta Bipin Thapa,PAN668645879
3,DLNLEG6218579,C00038863,KHOTANG FOODS PVT. LTD.,NaN,NaN,-9862720425,MANASLU HOSPITALITY PVT. LTD.,NaN,khotangfoods840@outlook.com,NaN,KHOTANG FOODS PVT. LTD.,PAN533918346
4,DLNIND1255130,R01651971,Adarsh,Bhakta,Lama,-9810012680,Adarsh Bhakta Lama,BINODRAYEE@GMAIL.COM,adarsh904@gmail.com,M,Adarsh Bhakta Lama,PAN331700070
...,...,...,...,...,...,...,...,...,...,...,...,...
120,DLNLEG4016980,C00004453,PALPA PHARMACEUTICALS PVT. LTD.,NaN,NaN,-9872632610,LUMBINI TRAVELS PVT. LTD.,NaN,palpapharmaceuticals564@outlook.com,NaN,PALPA PHARMACEUTICALS PVT. LTD.,PAN608753570
121,DLNIND8690282,R00625845,Ronika,Devi,Rai,-9854650440,Ronika Devi Rai,NaN,ronika219@gmail.com,F,Ronika Devi Rai,PAN234402002
122,DLNLEG9334212,R32157797,LUMBINI TRAVELS PVT. LTD.,NaN,NaN,-9858186332,PALPA HEALTHCARE PVT. LTD.,NaN,lumbinitravels925@outlook.com,NaN,LUMBINI TRAVELS PVT. LTD.,PAN353089449
123,DLNIND3694466,R30102616,Neeti,Saraswati,Limbu,-9881494422,Neeti Saraswati Limbu,NARAYANI.SHRESTHA@NICBANK.COM.NP,neeti318@gmail.com,F,Neeti Saraswati Limbu,PAN996196919
124,DLNLEG7265178,800520784,SINDHUPALCHOWK MEDIA PVT. LTD.,NaN,NaN,-9853587141,NEPAL HERITAGE TOURS PVT. LTD.,NaN,sindhupalchowkmedia799@outlook.com,NaN,SINDHUPALCHOWK MEDIA PVT. LTD.,PAN188513875

In [4]:
result = pd.merge(df_merchant_qr, df_acid_for, how='left', left_on='account_number',right_on='foracid',suffixes=('_p', '_a'))

result.columns

Index(['_id', 'name', 'doing_business_as', 'pan_number', 'mobile_number',
       'email_id', 'account_number', 'account_name', 'user_name', 'status',
       'stage', 'created_date', 'merchant_settlement_level',
       'is_instant_settlement', 'merchant_category', 'merchant_subcategory',
       'business_registered_org', 'is_vat', 'user_profile',
       'merchant_registration_type', 'reg_mode', 'business_type',
       'settlement_level', 'data_synced_date', 'remarks', 'branch_code',
       'branch_name', 'province', 'district', 'municipality', 'tole',
       'created_approve_date', 'modified_date', 'approved_date', 'approved_by',
       'modified_by', 'is_pan_registered', 'introduced_by',
       'business_registration_no', 'source_file_path', 'updated_at', 'acid',
       'acid_t', 'cif_id', 'foracid', 'foracid_t', 'pan', 'acct_num',
       'acct_name'],
      dtype='object')

In [5]:
print(result.shape)
print(df_merchant_qr.shape)

(29, 49)
(29, 41)

In [6]:
df_result = pd.merge(result, df_cif_mask, how='left', on='cif_id',suffixes=('_p', '_a'))

df_result['cif_id']

0     DLNLEG9370940
1     DLNLEG9966100
2     DLNLEG9101051
3     DLNLEG1805667
4     DLNLEG5604950
5     DLNLEG2266684
6     DLNLEG3286748
7     DLNLEG6566454
8     DLNLEG5919852
9     DLNLEG5063941
10    DLNLEG8246037
11    DLNLEG5646672
12    DLNLEG6465924
13    DLNLEG7265178
14    DLNLEG5924902
15    DLNLEG2990042
16    DLNLEG3756805
17    DLNLEG6576494
18    DLNLEG6576494
19    DLNLEG6576494
20    DLNLEG6576494
21    DLNLEG6576494
22    DLNLEG6576494
23    DLNIND5013653
24    DLNLEG6576494
25    DLNLEG6218579
26    DLNLEG1337370
27    DLNLEG1598748
28    DLNIND7227326
Name: cif_id, dtype: object

In [7]:
df_result.columns

Index(['_id', 'name_p', 'doing_business_as', 'pan_number', 'mobile_number',
       'email_id', 'account_number', 'account_name', 'user_name', 'status',
       'stage', 'created_date', 'merchant_settlement_level',
       'is_instant_settlement', 'merchant_category', 'merchant_subcategory',
       'business_registered_org', 'is_vat', 'user_profile',
       'merchant_registration_type', 'reg_mode', 'business_type',
       'settlement_level', 'data_synced_date', 'remarks', 'branch_code',
       'branch_name', 'province', 'district', 'municipality', 'tole',
       'created_approve_date', 'modified_date', 'approved_date', 'approved_by',
       'modified_by', 'is_pan_registered', 'introduced_by',
       'business_registration_no', 'source_file_path', 'updated_at', 'acid',
       'acid_t', 'cif_id', 'foracid', 'foracid_t', 'pan_p', 'acct_num',
       'acct_name', 'orgkey', 'cust_first_name', 'cust_middle_name',
       'cust_last_name', 'preferredphone', 'preferredname', 'preferredemail',
       'email', 'gender', 'name_a', 'pan_a'],
      dtype='object')

In [8]:
df_merchant_qr['name']=df_result['name_a'].values
df_merchant_qr['doing_business_as']=df_result['name_a'].values
df_merchant_qr['pan_number']=df_result['pan_a'].values
df_merchant_qr['mobile_number']=df_result['preferredphone'].values
df_merchant_qr['email_id']=df_result['email'].values
df_merchant_qr['account_number']=df_result['foracid_t'].values
df_merchant_qr['account_name']=df_result['name_a'].values
df_merchant_qr['user_name']=df_result['preferredphone'].values
df_merchant_qr

,_id,name,doing_business_as,pan_number,mobile_number,email_id,account_number,account_name,user_name,status,...,created_approve_date,modified_date,approved_date,approved_by,modified_by,is_pan_registered,introduced_by,business_registration_no,source_file_path,updated_at
0,43968,HIMAL DAIRY PRODUCTS PVT. LTD.,HIMAL DAIRY PRODUCTS PVT. LTD.,PAN931349773,-9899755984,himaldairyproducts393@outlook.com,FA5129878673917499,HIMAL DAIRY PRODUCTS PVT. LTD.,-9899755984,ACTIVE,...,2020-03-06T13:21:42,NaN,2020-03-06T13:21:42,NaN,NaN,NaN,KOTHIHAWA BRANCH,2457,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
1,8650,DLYTICA ACADEMY,DLYTICA ACADEMY,PAN200433423,-9833053483,dlyticaacademy500@outlook.com,FA7983505380425436,DLYTICA ACADEMY,-9833053483,ACTIVE,...,2019-04-28T09:53:04,NaN,2019-04-28T09:53:04,NaN,NaN,NaN,NaN,4709/072/073,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
2,306428,KAVREPALANCHOK MEDIA PVT. LTD.,KAVREPALANCHOK MEDIA PVT. LTD.,PAN871468252,-9829915866,kavrepalanchokmedia562@outlook.com,FA9003023957215959,KAVREPALANCHOK MEDIA PVT. LTD.,-9829915866,ACTIVE,...,2019-12-23T16:32:10,2020-04-22T17:03:58,2019-12-23T16:32:10,NaN,NaN,NaN,DAMAK CHOWK BRANCH,154/10016/5/4,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
3,32681,PATHIVARA LOGISTICS PVT. LTD.,PATHIVARA LOGISTICS PVT. LTD.,PAN629114031,-9847929209,pathivaralogistics755@outlook.com,FA4748279358343888,PATHIVARA LOGISTICS PVT. LTD.,-9847929209,ACTIVE,...,2020-02-24T18:02:53,NaN,2020-02-24T18:02:53,NaN,NaN,NaN,Bhaktapur,464/067/68,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
4,283430,JUMLA FOOD PRODUCTS PVT. LTD.,JUMLA FOOD PRODUCTS PVT. LTD.,PAN795534455,-9855214755,jumlafoodproducts402@outlook.com,FA7186585600099040,JUMLA FOOD PRODUCTS PVT. LTD.,-9855214755,ACTIVE,...,2019-12-06T14:29:45,NaN,2019-12-06T14:29:45,NaN,NaN,NaN,BIRGUNJ BRANCH,4330/029,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
5,75197,SAGARMATHA CLOTHING PVT. LTD.,SAGARMATHA CLOTHING PVT. LTD.,PAN940651973,-9846899379,sagarmathaclothing663@outlook.com,FA7093825707931983,SAGARMATHA CLOTHING PVT. LTD.,-9846899379,ACTIVE,...,2021-01-31T16:12:09,NaN,2021-01-31T16:12:09,NaN,NaN,NaN,THAMEL,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
6,335777,MYAGDI ENTERPRISES LTD.,MYAGDI ENTERPRISES LTD.,PAN903432729,-9822226101,myagdienterprises905@outlook.com,FA5680461078936753,MYAGDI ENTERPRISES LTD.,-9822226101,ACTIVE,...,2021-03-31T04:20:19,2022-05-30T14:32:50,2022-05-31T16:16:44,NIC_POONAM,NIC_TRIGENDRA,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
7,118824,PARSA TRADING PVT. LTD.,PARSA TRADING PVT. LTD.,PAN491523472,-9811736085,parsatrading914@outlook.com,FA9853744565679913,PARSA TRADING PVT. LTD.,-9811736085,ACTIVE,...,2021-02-04T10:41:01,2021-02-09T12:03:44,2021-02-04T10:41:01,NaN,NaN,NaN,TARAHARA BRANCH,14323/075/076,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
8,292127,RUPA SAVINGS AND CREDIT COOPERATIVE LTD.,RUPA SAVINGS AND CREDIT COOPERATIVE LTD.,PAN723809886,-9863483293,rupasavingsandcreditcooperative845@outlook.com,FA4639328509056038,RUPA SAVINGS AND CREDIT COOPERATIVE LTD.,-9863483293,ACTIVE,...,2019-12-12T11:13:57,NaN,2019-12-12T11:13:57,NaN,NaN,NaN,PARSYANG BRANCH,997/2073/074,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
9,122578,SYANGJA FOOTWEAR PVT. LTD.,SYANGJA FOOTWEAR PVT. LTD.,PAN392428656,-9863200191,syangjafootwear282@outlook.com,FA1491515342785562,SYANGJA FOOTWEAR PVT. LTD.,-9863200191,ACTIVE,...,2020-05-03T16:59:55,2021-06-13T16:37:10,2020-05-03T16:59:55,NaN,NaN,NaN,NEW ROAD BISHAL BAZAR BRANCH,17/2/2044,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
10,115625,DLYTICA HOSPITAL PVT. LTD.,DLYTICA HOSPITAL PVT. LTD.,PAN888268690,-9878494777,dlyticahospital731@outlook.com,FA3257804432259527,DLYTICA HOSPITAL PVT. LTD.,-9878494777,ACTIVE,...,2021-02-03T22:50:36,2021-02-04T15:33:41,2021-02-03T22:50:36,NaN,NaN,NaN,Hetauda,189492,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
11,101296,MANASLU HOSPITALITY PVT. LTD.,MANASLU HOSPITALITY PVT. LTD.,PAN280369345,-9892029057,manasluhospitality709@outlook.com,FA2922467209225100,MANASLU HOSPITALITY PVT. LTD.,-9892029057,ACTIVE,...,2021-02-03T09:39:10,NaN,2021-02-03T09:39:10,NaN,NaN,NaN,PHARPING,83325,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
12,135371,BIRATNAGAR AUTOMOBILES PVT. LTD.,BIRATNAGAR AUTOMOBILES PVT. LTD.,PAN952179235,-9845095898,biratnagarautomobiles930@outlook.com,FA8698709284689804,BIRATNAGAR AUTOMOBILES PVT. LTD.,-9845095898,ACTIVE,...,2021-03-15T19:20:12,2021-06-07T16:38:25,2021-03-15T19:20:12,NaN,NaN,NaN,TRIPURESWOR,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
13,207654,SINDHUPALCHOWK MEDIA PVT. LTD.,SINDHUPALCHOWK MEDIA PVT. LTD.,PAN188513875,-9853587141,sindhupalchowkmedia799@outlook.com,FA6389229208095535,SINDHUPALCHOWK MEDIA PVT. LTD.,-9853587141,ACTIVE,...,2021-06-07T12:51:20,NaN,2021-06-07T12:51:20,NaN,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
14,209188,SUNSARI MANUFACTURING LTD.,SUNSARI MANUFACTURING LTD.,PAN596302582,-9875670162,sunsarimanufacturing849@outlook.com,FA3813492651472021,SUNSARI MANUFACTURING LTD.,-9875670162,ACTIVE,...,2021-06-07T13:33:45,NaN,2021-06-07T13:33:45,NaN,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
15,151985,SARLAHI ENGINEERING PVT. LTD.,SARLAHI ENGINEERING PVT. LTD.,PAN608705773,-9829816196,sarlahiengineering869@outlook.com,FA6941359367497685,SARLAHI ENGINEERING PVT. LTD.,-9829816196,ACTIVE,...,2021-02-05T11:50:13,2021-02-11T11:07:05,2021-02-05T11:50:13,NaN,NaN,NaN,ILAM BRANCH,1156/075/076,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
16,132456,KANCHANJUNGA LOGISTICS PVT. LTD.,KANCHANJUNGA LOGISTICS PVT. LTD.,PAN668536553,-9899138452,kanchanjungalogistics925@outlook.com,FA3270201392445922,KANCHANJUNGA LOGISTICS PVT. LTD.,-9899138452,ACTIVE,...,2021-02-04T17:20:07,2021-02-08T10:35:08,2021-02-04T17:20:07,NaN,NaN,NaN,Battisputali,191412/74/075,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
17,1371827,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA8119659000961997,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-11-08T16:49:45,NaN,2023-11-08T16:49:45,NIC_PRANAW,NaN,1.0,mail by bishal ba_idhya,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
18,1372361,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA2085715034118759,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-11-17T14:18:56,2023-11-28T12:38:23,2023-11-28T12:39:44,NIC_REENA,NIC_PRANAW,1.0,mail by chabbi pant,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
19,1375058,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA7474483400900345,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-11-27T12:04:28,2023-11-28T12:39:16,2023-11-28T12:39:37,NIC_REENA,NIC_PRANAW,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
20,1332961,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA6722140254743665,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-09-12T17:02:13,2023-09-13T09:33:03,2023-09-13T09:33:28,NIC_TRIGENDRA,NIC_SUSHMA,1.0,67947,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
21,1336233,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA6331816547052275,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-09-15T11:17:47,2023-09-17T11:00:31,2023-09-17T11:00:55,NIC_REENA,NIC_SUSHMA,1.0,68064,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
22,1349259,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA7724894015587081,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2023-09-26T16:22:08,2023-09-26T16:23:35,2023-09-26T16:24:35,NICA_DEVI,NIC_BISHAL,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
23,1236923,Mikma Hari Lama,Mikma Hari Lama,PAN106648673,-9854768199,mikma924@gmail.com,FA3354631320292183,Mikma Hari Lama,-9854768199,ACTIVE,...,2023-06-07T16:15:49,NaN,2023-06-07T16:15:49,SYSTEM,NaN,1.0,60225,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
24,1422388,NEPAL AIRLINES LTD.,NEPAL AIRLINES LTD.,PAN813377590,-9856246804,nepalairlines939@outlook.com,FA1033345099266430,NEPAL AIRLINES LTD.,-9856246804,ACTIVE,...,2024-02-02T12:00:35,NaN,2024-02-02T12:00:35,NIC_POONAM,NaN,0.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
25,187208,KHOTANG FOODS PVT. LTD.,KHOTANG FOODS PVT. LTD.,PAN533918346,-9862720425,khotangfoods840@outlook.com,FA1420124971439178,KHOTANG FOODS PVT. LTD.,-9862720425,ACTIVE,...,2021-06-02T13:31:12,NaN,2021-06-02T13:31:12,NaN,NaN,NaN,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
26,1058073,ROLPA CONSTRUCTIONS PVT. LTD.,ROLPA CONSTRUCTIONS PVT. LTD.,PAN324979852,-9842730869,rolpaconstructions648@outlook.com,FA3141891666109954,ROLPA CONSTRUCTIONS PVT. LTD.,-9842730869,ACTIVE,...,2022-11-27T15:33:38,NaN,2022-11-27T15:33:38,SYSTEM,NaN,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
27,1042227,SAGARMATHA TRADERS PVT. LTD.,SAGARMATHA TRADERS PVT. LTD.,PAN606494169,-9848709913,sagarmathatraders388@outlook.com,FA8244589281955200,SAGARMATHA TRADERS PVT. LTD.,-9848709913,ACTIVE,...,2022-11-09T15:27:17,NaN,2022-11-09T15:27:17,SYSTEM,NaN,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
28,680648,Sunanda Bishnu Rai,Sunanda Bishnu Rai,PAN613246502,-9886187930,sunanda615@gmail.com,FA7587884540430954,Sunanda Bishnu Rai,-9886187930,ACTIVE,...,2022-04-12T17:06:42,NaN,2022-04-12T17:06:42,SYSTEM,NaN,1.0,NaN,NaN,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904

In [9]:
df_merchant_qr['merchant_subcategory']

0                         School/Colleges/ Universities
1                          Jewelry and Silverware Shops
2                                           Enterprises
3               Communication Centre (E.g. Cyber Cafes)
4                                Family Clothing Stores
5                                           Enterprises
6                                                  NONE
7     Furniture, Furniture Repair, and Furniture Ref...
8                                            Industries
9                    Pharmacies (Wholesale and Retails)
10                               Construction materials
11                                              TRADERS
12                                              TRADERS
13    Grocery & Department Store (E.g. KK Mart, Big ...
14    Grocery & Department Store (E.g. KK Mart, Big ...
15                                          Enterprises
16                                              TRADERS
17       Government Services (Not Elsewhere Classified)
18       Government Services (Not Elsewhere Classified)
19       Government Services (Not Elsewhere Classified)
20                                           Paan pasal
21    Telecommunication Service Prov_iders (E.g. Nce...
22    Telecommunication Service Prov_iders (E.g. Nce...
23                        Eating places and Restaurants
24       Government Services (Not Elsewhere Classified)
25    Furniture, Furniture Repair, and Furniture Ref...
26                                                 NONE
27                                                 NONE
28                                      Clothing Stores
Name: merchant_subcategory, dtype: object

In [10]:
df_merchant_qr['merchant_category']

0     Professional Services and Membership Organizat...
1                                 Miscellaneous Outlets
2                                                  NONE
3                                 Miscellaneous Outlets
4                                      Clothing Outlets
5                                                  NONE
6                                                  NONE
7                                       Repair Services
8                                                  NONE
9                                 Miscellaneous Outlets
10                                       Retail Outlets
11                                       Retail Outlets
12                                       Retail Outlets
13                                       Retail Outlets
14                                       Retail Outlets
15                                                 NONE
16                                       Retail Outlets
17                                   Government Service
18                                   Government Service
19                                   Government Service
20                                       Retail Outlets
21                                            Utilities
22                                            Utilities
23                                Miscellaneous Outlets
24                                   Government Service
25                                      Repair Services
26                                                 NONE
27                                                 NONE
28                                     Clothing Outlets
Name: merchant_category, dtype: object

In [11]:
df_merchant_qr['business_registered_org']

0             Rural/Municipality
1     Office of Company Register
2         Department of commerce
3         Department of commerce
4         Department of commerce
5     Office of Company Register
6     Office of Company Register
7     Office of Company Register
8         Department of commerce
9         Department of commerce
10    Office of Company Register
11        Department of commerce
12        Department of commerce
13                         Other
14                         Other
15        Department of commerce
16    Office of Company Register
17            Rural/Municipality
18            Rural/Municipality
19            Rural/Municipality
20                         Other
21            Rural/Municipality
22                         Other
23            Rural/Municipality
24                  Unregistered
25                         Other
26            Rural/Municipality
27            Rural/Municipality
28                         Other
Name: business_registered_org, dtype: object

In [12]:
df_merchant_qr['name']

0               HIMAL DAIRY PRODUCTS PVT. LTD.
1                              DLYTICA ACADEMY
2               KAVREPALANCHOK MEDIA PVT. LTD.
3                PATHIVARA LOGISTICS PVT. LTD.
4                JUMLA FOOD PRODUCTS PVT. LTD.
5                SAGARMATHA CLOTHING PVT. LTD.
6                      MYAGDI ENTERPRISES LTD.
7                      PARSA TRADING PVT. LTD.
8     RUPA SAVINGS AND CREDIT COOPERATIVE LTD.
9                   SYANGJA FOOTWEAR PVT. LTD.
10                  DLYTICA HOSPITAL PVT. LTD.
11               MANASLU HOSPITALITY PVT. LTD.
12            BIRATNAGAR AUTOMOBILES PVT. LTD.
13              SINDHUPALCHOWK MEDIA PVT. LTD.
14                  SUNSARI MANUFACTURING LTD.
15               SARLAHI ENGINEERING PVT. LTD.
16            KANCHANJUNGA LOGISTICS PVT. LTD.
17                         NEPAL AIRLINES LTD.
18                         NEPAL AIRLINES LTD.
19                         NEPAL AIRLINES LTD.
20                         NEPAL AIRLINES LTD.
21                         NEPAL AIRLINES LTD.
22                         NEPAL AIRLINES LTD.
23                             Mikma Hari Lama
24                         NEPAL AIRLINES LTD.
25                     KHOTANG FOODS PVT. LTD.
26               ROLPA CONSTRUCTIONS PVT. LTD.
27                SAGARMATHA TRADERS PVT. LTD.
28                          Sunanda Bishnu Rai
Name: name, dtype: object

In [13]:
# Your full mapping dictionary
merchant_mapping = {
    "HIMAL DAIRY PRODUCTS PVT. LTD.": {
        "merchant_subcategory": "Grocery & Dairy",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "DLYTICA ACADEMY": {
        "merchant_subcategory": "School/Colleges/ Universities",
        "merchant_category": "Professional Services and Membership",
        "business_registered_org": "Rural/Municipality"
    },
    "KAVREPALANCHOK MEDIA PVT. LTD.": {
        "merchant_subcategory": "Communication Centre",
        "merchant_category": "Miscellaneous Outlets",
        "business_registered_org": "Office of Company Register"
    },
    "PATHIVARA LOGISTICS PVT. LTD.": {
        "merchant_subcategory": "Industries",
        "merchant_category": "Repair Services",
        "business_registered_org": "Department of commerce"
    },
    "JUMLA FOOD PRODUCTS PVT. LTD.": {
        "merchant_subcategory": "Grocery & Department Store",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "SAGARMATHA CLOTHING PVT. LTD.": {
        "merchant_subcategory": "Clothing Store",
        "merchant_category": "clothing Outlets",
        "business_registered_org": "Department of commerce"
    },
    "MYAGDI ENTERPRISES LTD.": {
        "merchant_subcategory": "Enterprise",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Office of Company Register"
    },
    "PARSA TRADING PVT. LTD.": {
        "merchant_subcategory": "Repair",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Office of Company Register"
    },
    "RUPA SAVINGS AND CREDIT COOPERATIVE LTD.": {
        "merchant_subcategory": "service",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "SYANGJA FOOTWEAR PVT. LTD.": {
        "merchant_subcategory": "Clothing",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "DLYTICA HOSPITAL PVT. LTD.": {
        "merchant_subcategory": "Government Services (Not Elsewhere Classified",
        "merchant_category": "Government Service",
        "business_registered_org": "Rural/Municipality"
    },
    "MANASLU HOSPITALITY PVT. LTD.": {
        "merchant_subcategory": "Government Services (Not Elsewhere Classified)",
        "merchant_category": "Government Service",
        "business_registered_org": "Rural/Municipality"
    },
    "BIRATNAGAR AUTOMOBILES PVT. LTD.": {
        "merchant_subcategory": "",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "SINDHUPALCHOWK MEDIA PVT. LTD.": {
        "merchant_subcategory": "Communication Centre (E.g. Cyber Cafes)",
        "merchant_category": "Miscellaneous Outlets",
        "business_registered_org": "Office of Company Register"
    },
    "SUNSARI MANUFACTURING LTD.": {
        "merchant_subcategory": "Grocery & Department Store (E.g. KK Mart, Big ...)",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "SARLAHI ENGINEERING PVT. LTD.": {
        "merchant_subcategory": "Enterprise",
        "merchant_category": "None",
        "business_registered_org": "Department of commerce"
    },
    "KANCHANJUNGA LOGISTICS PVT. LTD.": {
        "merchant_subcategory": "Industries",
        "merchant_category": "Repair Services",
        "business_registered_org": "Department of commerce"
    },
    "NEPAL AIRLINES LTD.": {
        "merchant_subcategory": "Government Services (Not Elsewhere Classified)",
        "merchant_category": "Government Service",
        "business_registered_org": "Rural/Municipality"
    },
    "Mikma Hari Lama": {
        "merchant_subcategory": "TRADERS",
        "merchant_category": "other",
        "business_registered_org": "Other"
    },
    "KHOTANG FOODS PVT. LTD.": {
        "merchant_subcategory": "Grocery & Department Store (E.g. KK Mart, Big ...)",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "ROLPA CONSTRUCTIONS PVT. LTD.": {
        "merchant_subcategory": "Enterprise",
        "merchant_category": "None",
        "business_registered_org": "Department of commerce"
    },
    "SAGARMATHA TRADERS PVT. LTD.": {
        "merchant_subcategory": "Grocery & Department Store (E.g. KK Mart, Big ...)",
        "merchant_category": "Retail Outlets",
        "business_registered_org": "Department of commerce"
    },
    "Sunanda Bishnu Rai": {
        "merchant_subcategory": "TRADERS",
        "merchant_category": "other",
        "business_registered_org": "Other"
    }
}

# Function to update each column based on name
def update_columns(row):
    name = row["name"]
    if name in merchant_mapping:
        row["merchant_subcategory"] = merchant_mapping[name]["merchant_subcategory"]
        row["merchant_category"] = merchant_mapping[name]["merchant_category"]
        row["business_registered_org"] = merchant_mapping[name]["business_registered_org"]
    return row

# Apply the function row-wise
df_merchant_qr = df_merchant_qr.apply(update_columns, axis=1)

In [14]:
df_merchant_qr.head()

,_id,name,doing_business_as,pan_number,mobile_number,email_id,account_number,account_name,user_name,status,...,created_approve_date,modified_date,approved_date,approved_by,modified_by,is_pan_registered,introduced_by,business_registration_no,source_file_path,updated_at
0,43968,HIMAL DAIRY PRODUCTS PVT. LTD.,HIMAL DAIRY PRODUCTS PVT. LTD.,PAN931349773,-9899755984,himaldairyproducts393@outlook.com,FA5129878673917499,HIMAL DAIRY PRODUCTS PVT. LTD.,-9899755984,ACTIVE,...,2020-03-06T13:21:42,NaN,2020-03-06T13:21:42,NaN,NaN,NaN,KOTHIHAWA BRANCH,2457,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
1,8650,DLYTICA ACADEMY,DLYTICA ACADEMY,PAN200433423,-9833053483,dlyticaacademy500@outlook.com,FA7983505380425436,DLYTICA ACADEMY,-9833053483,ACTIVE,...,2019-04-28T09:53:04,NaN,2019-04-28T09:53:04,NaN,NaN,NaN,NaN,4709/072/073,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
2,306428,KAVREPALANCHOK MEDIA PVT. LTD.,KAVREPALANCHOK MEDIA PVT. LTD.,PAN871468252,-9829915866,kavrepalanchokmedia562@outlook.com,FA9003023957215959,KAVREPALANCHOK MEDIA PVT. LTD.,-9829915866,ACTIVE,...,2019-12-23T16:32:10,2020-04-22T17:03:58,2019-12-23T16:32:10,NaN,NaN,NaN,DAMAK CHOWK BRANCH,154/10016/5/4,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
3,32681,PATHIVARA LOGISTICS PVT. LTD.,PATHIVARA LOGISTICS PVT. LTD.,PAN629114031,-9847929209,pathivaralogistics755@outlook.com,FA4748279358343888,PATHIVARA LOGISTICS PVT. LTD.,-9847929209,ACTIVE,...,2020-02-24T18:02:53,NaN,2020-02-24T18:02:53,NaN,NaN,NaN,Bhaktapur,464/067/68,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
4,283430,JUMLA FOOD PRODUCTS PVT. LTD.,JUMLA FOOD PRODUCTS PVT. LTD.,PAN795534455,-9855214755,jumlafoodproducts402@outlook.com,FA7186585600099040,JUMLA FOOD PRODUCTS PVT. LTD.,-9855214755,ACTIVE,...,2019-12-06T14:29:45,NaN,2019-12-06T14:29:45,NaN,NaN,NaN,BIRGUNJ BRANCH,4330/029,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904

In [15]:
df_merchant_qr[['name','merchant_subcategory','merchant_category','business_registered_org']]

,name,merchant_subcategory,merchant_category,business_registered_org
0,HIMAL DAIRY PRODUCTS PVT. LTD.,Grocery & Dairy,Retail Outlets,Department of commerce
1,DLYTICA ACADEMY,School/Colleges/ Universities,Professional Services and Membership,Rural/Municipality
2,KAVREPALANCHOK MEDIA PVT. LTD.,Communication Centre,Miscellaneous Outlets,Office of Company Register
3,PATHIVARA LOGISTICS PVT. LTD.,Industries,Repair Services,Department of commerce
4,JUMLA FOOD PRODUCTS PVT. LTD.,Grocery & Department Store,Retail Outlets,Department of commerce
5,SAGARMATHA CLOTHING PVT. LTD.,Clothing Store,clothing Outlets,Department of commerce
6,MYAGDI ENTERPRISES LTD.,Enterprise,Retail Outlets,Office of Company Register
7,PARSA TRADING PVT. LTD.,Repair,Retail Outlets,Office of Company Register
8,RUPA SAVINGS AND CREDIT COOPERATIVE LTD.,service,Retail Outlets,Department of commerce
9,SYANGJA FOOTWEAR PVT. LTD.,Clothing,Retail Outlets,Department of commerce
10,DLYTICA HOSPITAL PVT. LTD.,Government Services (Not Elsewhere Classified,Government Service,Rural/Municipality
11,MANASLU HOSPITALITY PVT. LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
12,BIRATNAGAR AUTOMOBILES PVT. LTD.,,Retail Outlets,Department of commerce
13,SINDHUPALCHOWK MEDIA PVT. LTD.,Communication Centre (E.g. Cyber Cafes),Miscellaneous Outlets,Office of Company Register
14,SUNSARI MANUFACTURING LTD.,"Grocery & Department Store (E.g. KK Mart, Big ...",Retail Outlets,Department of commerce
15,SARLAHI ENGINEERING PVT. LTD.,Enterprise,None,Department of commerce
16,KANCHANJUNGA LOGISTICS PVT. LTD.,Industries,Repair Services,Department of commerce
17,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
18,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
19,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
20,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
21,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
22,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
23,Mikma Hari Lama,TRADERS,other,Other
24,NEPAL AIRLINES LTD.,Government Services (Not Elsewhere Classified),Government Service,Rural/Municipality
25,KHOTANG FOODS PVT. LTD.,"Grocery & Department Store (E.g. KK Mart, Big ...",Retail Outlets,Department of commerce
26,ROLPA CONSTRUCTIONS PVT. LTD.,Enterprise,None,Department of commerce
27,SAGARMATHA TRADERS PVT. LTD.,"Grocery & Department Store (E.g. KK Mart, Big ...",Retail Outlets,Department of commerce
28,Sunanda Bishnu Rai,TRADERS,other,Other

In [16]:
df_merchant_qr = df_merchant_qr.drop(["source_file_path"], axis=1)

df_merchant_qr.head()

,_id,name,doing_business_as,pan_number,mobile_number,email_id,account_number,account_name,user_name,status,...,tole,created_approve_date,modified_date,approved_date,approved_by,modified_by,is_pan_registered,introduced_by,business_registration_no,updated_at
0,43968,HIMAL DAIRY PRODUCTS PVT. LTD.,HIMAL DAIRY PRODUCTS PVT. LTD.,PAN931349773,-9899755984,himaldairyproducts393@outlook.com,FA5129878673917499,HIMAL DAIRY PRODUCTS PVT. LTD.,-9899755984,ACTIVE,...,TILOTTAMA 14,2020-03-06T13:21:42,NaN,2020-03-06T13:21:42,NaN,NaN,NaN,KOTHIHAWA BRANCH,2457,2024-08-07 05:23:35.904
1,8650,DLYTICA ACADEMY,DLYTICA ACADEMY,PAN200433423,-9833053483,dlyticaacademy500@outlook.com,FA7983505380425436,DLYTICA ACADEMY,-9833053483,ACTIVE,...,BANDIPUR,2019-04-28T09:53:04,NaN,2019-04-28T09:53:04,NaN,NaN,NaN,NaN,4709/072/073,2024-08-07 05:23:35.904
2,306428,KAVREPALANCHOK MEDIA PVT. LTD.,KAVREPALANCHOK MEDIA PVT. LTD.,PAN871468252,-9829915866,kavrepalanchokmedia562@outlook.com,FA9003023957215959,KAVREPALANCHOK MEDIA PVT. LTD.,-9829915866,ACTIVE,...,DAMAK 5,2019-12-23T16:32:10,2020-04-22T17:03:58,2019-12-23T16:32:10,NaN,NaN,NaN,DAMAK CHOWK BRANCH,154/10016/5/4,2024-08-07 05:23:35.904
3,32681,PATHIVARA LOGISTICS PVT. LTD.,PATHIVARA LOGISTICS PVT. LTD.,PAN629114031,-9847929209,pathivaralogistics755@outlook.com,FA4748279358343888,PATHIVARA LOGISTICS PVT. LTD.,-9847929209,ACTIVE,...,Bhulancha,2020-02-24T18:02:53,NaN,2020-02-24T18:02:53,NaN,NaN,NaN,Bhaktapur,464/067/68,2024-08-07 05:23:35.904
4,283430,JUMLA FOOD PRODUCTS PVT. LTD.,JUMLA FOOD PRODUCTS PVT. LTD.,PAN795534455,-9855214755,jumlafoodproducts402@outlook.com,FA7186585600099040,JUMLA FOOD PRODUCTS PVT. LTD.,-9855214755,ACTIVE,...,ALKHIYA ROAD-4 BIRGUNJ,2019-12-06T14:29:45,NaN,2019-12-06T14:29:45,NaN,NaN,NaN,BIRGUNJ BRANCH,4330/029,2024-08-07 05:23:35.904

In [17]:
import re

df_merchant_qr[['approved_by','modified_by']] = df_merchant_qr[['approved_by','modified_by']].map(
    lambda x: re.sub(r'(?i)nic', 'SAGARMATHA', x) if isinstance(x, str) else x
)

In [18]:
df_merchant_qr.to_csv("merchant_details_masked.csv",index=False)