In [ ]:
import pandas as pd
df_merchant=pd.read_excel("merchant_details.xlsx")
df_merchant.head()

,_id,name,doing_business_as,pan_number,mobile_number,email_id,account_number,account_name,user_name,status,...,created_approve_date,modified_date,approved_date,approved_by,modified_by,is_pan_registered,introduced_by,business_registration_no,source_file_path,updated_at
0,43968,SHREE TIKULIGADH MA VI,SHREE TIKULIGADH MA VI,912345704.0,9857015912,9857015912@nica.com,F141000445852402,SHREE TIKULIGADH MA VI,9857015912@nica.com,ACTIVE,...,2020-03-06T13:21:42,NaN,2020-03-06T13:21:42,NaN,NaN,NaN,KOTHIHAWA BRANCH,2457,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
1,8650,ARJUN SUNCHANDI UDHYOG,ARJUN SUNCHANDI UDHYOG,602205809.0,9856042369,sunitasunar352@gmail.com,E641000443952402,ARJUN SUNCHANDI UDHYOG,sunitasunar352@gmail.com,ACTIVE,...,2019-04-28T09:53:04,NaN,2019-04-28T09:53:04,NaN,NaN,NaN,NaN,4709/072/073,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
2,306428,PINKY KABADI PASAL,PINKY KABADI PASAL,301463056.0,9815993973,sekh@gmail.com,P541000445452402,PINKY KABADI PASAL,sekh@gmail.com,ACTIVE,...,2019-12-23T16:32:10,2020-04-22T17:03:58,2019-12-23T16:32:10,NaN,NaN,NaN,DAMAK CHOWK BRANCH,154/10016/5/4,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
3,32681,CRYSTAL OFFSET PRESS,CRYSTAL OFFSET PRESS,304298275.0,9843159014,crystal.press6@gmail.com,0841827246052401,CRYSTAL OFFSET PRESS,crystal.press6@gmail.com,ACTIVE,...,2020-02-24T18:02:53,NaN,2020-02-24T18:02:53,NaN,NaN,NaN,Bhaktapur,464/067/68,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904
4,283430,MUNNI LAL MANGI LAL,MUNNI LAL MANGI LAL,301454342.0,9855022111,9855022111@gmail.com,2240133473524004,MUNNI LAL MANGI LAL,9855022111@gmail.com,ACTIVE,...,2019-12-06T14:29:45,NaN,2019-12-06T14:29:45,NaN,NaN,NaN,BIRGUNJ BRANCH,4330/029,s3a://ai360nica/data/bronze/mongodb_nifi/qr/ni...,2024-08-07 05:23:35.904

In [ ]:
df_acid_for=pd.read_csv("")